In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('weather_play.csv')
df

     Weather  Temp Play
0      Sunny   Hot   No
1      Sunny   Hot   No
2   Overcast   Hot  Yes
3      Rainy  Mild  Yes
4      Rainy  Cool  Yes
5      Rainy  Cool   No
6   Overcast  Cool  Yes
7      Sunny  Mild   No
8      Sunny  Cool  Yes
9      Rainy  Mild  Yes
10     Sunny  Mild  Yes
11  Overcast  Mild  Yes
12  Overcast   Hot  Yes
13     Rainy  Mild   No

In [5]:
df['Play'].value_counts()

Play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py=9/14
pn=5/14

In [7]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [8]:
#Weather
pd.crosstab(df['Weather'],df['Play'])

Play      No  Yes
Weather
Overcast   0    4
Rainy      2    3
Sunny      3    2

In [9]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [10]:
#Temp
pd.crosstab(df['Temp'],df['Play'])

Play  No  Yes
Temp
Cool   1    3
Hot    2    2
Mild   2    4

In [11]:
pcn=1/5
phn=2/5
pmn=2/5

pcy=3/9
phy=2/9
pmy=4/9

In [13]:
#Weather=Rainy,Temperature=Cool
Pyes=py*pry*pcy
Pno=pn*prn*pcn
print(Pyes)
print(Pno)

0.07142857142857142
0.028571428571428577

In [14]:
#Weather=Rainy,Temperature=Cool,Play=Yes