In [48]:
import pandas as pd

In [49]:
df1=pd.read_csv('matches.csv')
df1

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [50]:
df2=pd.read_csv('deliveries.csv')
df2

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [51]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [52]:
df2.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(5)

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [53]:
runs=df2.groupby('batsman')

In [54]:
runs.get_group('V Kohli').shape

(3494, 21)

In [55]:
mask=df2['batsman_runs']==6
new=df2[mask]
new

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150395,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,2,V Kohli,CH Gayle,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150428,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,15,5,SR Watson,KL Rahul,MC Henriques,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150440,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [56]:
new.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(5)

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
V Kohli      160
DA Warner    160
Name: batsman_runs, dtype: int64

In [57]:
mask=df2['batsman']=='V Kohli'
new_mask=df2[mask]
new_mask

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [58]:
new_mask.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).head(5)

bowling_team
Chennai Super Kings    706
Delhi Daredevils       661
Kings XI Punjab        483
Mumbai Indians         447
Sunrisers Hyderabad    439
Name: batsman_runs, dtype: int64

In [59]:
def run_score(batsman_name):
    mask=df2['batsman']==batsman_name
    new_mask=df2[mask]
    return new_mask.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).head(1)

In [60]:
run_score('MS Dhoni')

bowling_team
Royal Challengers Bangalore    608
Name: batsman_runs, dtype: int64

In [61]:
mask=df2['batsman']=='V Kohli'
new_mask=df2[mask]
new_mask

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [62]:
print('Total runs scored by Virat Kohli in ten years:',new_mask['total_runs'].sum())

Total runs scored by Virat Kohli in ten years: 4588

In [63]:
print(df2['batsman_runs'].sum())

183929

In [64]:
mask=df2['batsman_runs']==4
new_mask=df2[mask]
new_mask.shape[0]

17033

In [65]:
mask=df2['batsman_runs']==6
new_mask=df2[mask]
new_mask.shape[0]

6523

In [66]:
df2.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(1)

batsman
SK Raina    4548
Name: batsman_runs, dtype: int64

In [67]:
df2.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
SK Raina          4548
V Kohli           4423
RG Sharma         4207
G Gambhir         4132
DA Warner         4014
RV Uthappa        3778
CH Gayle          3651
S Dhawan          3561
MS Dhoni          3560
AB de Villiers    3486
Name: batsman_runs, dtype: int64

In [68]:
df2.groupby('bowler')['ball'].count().sort_values(ascending=False).head(1)

bowler
Harbhajan Singh    2989
Name: ball, dtype: int64

In [69]:
df2.groupby('batsman')['ball'].count().sort_values(ascending=False).head(1)

batsman
V Kohli    3494
Name: ball, dtype: int64

In [70]:
df2.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False).head(1)

batting_team
Mumbai Indians    24521
Name: total_runs, dtype: int64

In [71]:
mask=df2['batsman_runs']==6
new_mask=df2[mask]
new_mask.groupby('batting_team')['batsman_runs'].count().sort_values(ascending=False).head(1)

batting_team
Royal Challengers Bangalore    935
Name: batsman_runs, dtype: int64

In [72]:
mask=df2['batsman_runs']==4
new_mask=df2[mask]
new_mask.groupby('batting_team')['batsman_runs'].count().sort_values(ascending=False).head(1)

batting_team
Mumbai Indians    2145
Name: batsman_runs, dtype: int64

In [73]:
runs=df2.groupby('batsman')['batsman_runs'].sum()

In [74]:
balls = df2[df2['wide_runs'] == 0].groupby('batsman').size()

In [75]:
striker_rate=(runs/balls)*100

In [76]:
striker_rate

batsman
A Ashish Reddy    145.077720
A Chandila         57.142857
A Chopra           74.647887
A Choudhary       125.000000
A Flintoff        116.981132
                     ...
YV Takawale       107.865169
Yashpal Singh      71.212121
Younis Khan        42.857143
Yuvraj Singh      131.256332
Z Khan             82.978723
Length: 461, dtype: float64

In [77]:
striker_rate.sort_values(ascending=False).head(10)

batsman
DL Chahar        233.333333
Umar Gul         205.263158
RS Sodhi         200.000000
BCJ Cutting      187.878788
CR Brathwaite    179.245283
LJ Wright        176.666667
AJ Tye           176.666667
Shahid Afridi    176.086957
I Malhotra       175.000000
SN Khan          173.529412
dtype: float64

In [78]:
striker_rate[(striker_rate>150) & (balls>=200)]

batsman
AD Russell    173.413897
CA Lynn       158.024691
CH Gayle      151.556663
CH Morris     165.660377
GJ Maxwell    164.304813
KH Pandya     158.415842
RR Pant       151.206434
V Sehwag      155.441595
dtype: float64

In [79]:
runs_conceded=df2.groupby('bowler')[['batsman_runs','wide_runs','noball_runs']].sum().sum(axis=1)
runs_conceded

bowler
A Ashish Reddy     396
A Chandila         242
A Choudhary        144
A Flintoff         105
A Kumble          1058
                  ...
YA Abdulla         307
YK Pathan         1393
YS Chahal         1569
Yuvraj Singh      1054
Z Khan            2782
Length: 356, dtype: int64

#### Economy Rate=Runs Conceded/Overs Bowled

In [80]:
legal_balls=df2[(df2['wide_runs']==0) & (df2['noball_runs']==0)]
balls=legal_balls.groupby('bowler').size()
overs_bowled=balls/6
overs_bowled

bowler
A Ashish Reddy     43.666667
A Chandila         39.000000
A Choudhary        16.833333
A Flintoff         11.000000
A Kumble          160.833333
                     ...
YA Abdulla         34.833333
YK Pathan         188.166667
YS Chahal         198.500000
Yuvraj Singh      142.833333
Z Khan            366.666667
Length: 356, dtype: float64

In [81]:
economy_rate=runs_conceded/overs_bowled

In [82]:
economy_rate

bowler
A Ashish Reddy    9.068702
A Chandila        6.205128
A Choudhary       8.554455
A Flintoff        9.545455
A Kumble          6.578238
                    ...
YA Abdulla        8.813397
YK Pathan         7.403012
YS Chahal         7.904282
Yuvraj Singh      7.379230
Z Khan            7.587273
Length: 356, dtype: float64

In [83]:
economy_rate[(economy_rate < 7)&(overs_bowled>=20)].sort_values(ascending=False)

bowler
Harbhajan Singh      6.957862
AD Mascarenhas       6.935065
R Rampaul            6.917910
J Botha              6.916427
M Ntini              6.914286
SL Malinga           6.865520
DL Vettori           6.779923
DW Steyn             6.747093
RE van der Merwe     6.744921
AJ Tye               6.714286
M Muralitharan       6.698953
Rashid Khan          6.629630
R Tewatia            6.619048
GD McGrath           6.611111
FH Edwards           6.600000
A Kumble             6.578238
R Ashwin             6.547598
SM Pollock           6.543478
J Yadav              6.533333
SMSM Senanayake      6.531250
Sohail Tanvir        6.461538
SP Narine            6.344899
A Chandila           6.205128
Washington Sundar    6.166667
dtype: float64

In [84]:
df2['dismissal_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'caught and bowled',
       'stumped', 'retired hurt', 'hit wicket', 'obstructing the field'],
      dtype=object)

In [85]:
out=df2[(df2['player_dismissed'].notna())&(~df2['dismissal_kind'].isin(['run out','retired hurt','obstructing the field']))]

In [86]:
out.groupby('bowler').size().sort_values(ascending=False)

bowler
SL Malinga           154
A Mishra             134
Harbhajan Singh      127
PP Chawla            126
DJ Bravo             122
                    ...
B Laughlin             1
Harmeet Singh (2)      1
PM Sarvesh Kumar       1
AM Rahane              1
LMP Simmons            1
Length: 310, dtype: int64

In [87]:
df2['player_dismissed'].value_counts().sort_values(ascending=False).head(1)

player_dismissed
SK Raina    134
Name: count, dtype: int64

In [88]:
df2[df2['dismissal_kind']=='caught'].groupby('fielder').size().sort_values(ascending=False).head(1)

fielder
KD Karthik    88
dtype: int64

In [89]:
df2['dismissal_kind'].value_counts().head(1)

dismissal_kind
caught    4373
Name: count, dtype: int64

In [90]:
df2.groupby('bowling_team')['extra_runs'].sum().sort_values(ascending=False).head(1)

bowling_team
Mumbai Indians    1397
Name: extra_runs, dtype: int64

In [96]:
new_delivery=df2.merge(df1,left_on='match_id',right_on='id')

In [105]:
new_delivery.groupby(['season','batsman'])['batsman_runs'].sum().sort_values(ascending=False).reset_index().drop_duplicates(subset='season',keep='first').sort_values('season')[['season','batsman']]

    season       batsman
10    2008      SE Marsh
14    2009     ML Hayden
9     2010  SR Tendulkar
11    2011      CH Gayle
3     2012      CH Gayle
2     2013    MEK Hussey
6     2014    RV Uthappa
17    2015     DA Warner
0     2016       V Kohli
7     2017     DA Warner